version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.9-cli
      - image: circleci/mysql:5.5.54

    working_directory: ~/repo

    steps:
      - run: sudo docker-php-ext-install mysqli
      - run: sudo docker-php-ext-install pdo_mysql

      - checkout

      - run: echo '{"host":"127.0.0.1","dbname":"circle_test","user":"root","password":""}' > htdocs/config/db.conf

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: php bin/db.php migrate
      - run: echo '{"host":"127.0.0.1","dbname":"circle","user":"root","password":""}' > htdocs/config/db.conf
      - run: make ci
